### ISSUE TITLE
Mod is not working at all...

### ISSUE THREAD

**Issue by CatsArmy** [willis81808/LethalCompany-AutoWalk#3]
Ive now tried to use the mod with only what it depends on and it doesnt work...

**Comment by CatsArmy** [comment]
I am going to create a pull request please accpet it i fixed both of the issues i brought up

**Comment by CatsArmy** [comment]
also sorry if your going to have to change a little bit of the pr as i had a bit of trouble getting the mod building on my pc so yeah

**Comment by willis81808** [comment]
Issue has been identified to be caused by a defect in the LethalCompany Input Utils.
Fixed in version 0.0.4
